"""add_position_fields_to_agents

Revision ID: 12f1cab0500b
Revises: 499e649950be
Create Date: 2025-11-03 21:04:14.499925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f1cab0500b'
down_revision: Union[str, None] = '499e649950be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('position_x', sa.Float(), nullable=True))
    op.add_column('agents', sa.Column('position_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'position_y')
    op.drop_column('agents', 'position_x')
    # ### end Alembic commands ###
