"""add_photo_injection_fields

Revision ID: b927dc021cd7
Revises: a39b4c5d2feb
Create Date: 2025-11-04 17:15:39.562757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b927dc021cd7'
down_revision: Union[str, None] = 'a39b4c5d2feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversation_messages_from_agent_id', table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_run_id', table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_timestamp', table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_to_agent_id', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.add_column('agents', sa.Column('photo_injection_enabled', sa.String(), nullable=True, server_default='false'))
    op.add_column('agents', sa.Column('photo_injection_features', sa.JSON(), nullable=True, server_default='[]'))
    # Set default values for existing rows
    op.execute("UPDATE agents SET photo_injection_enabled = 'false' WHERE photo_injection_enabled IS NULL")
    op.execute("UPDATE agents SET photo_injection_features = '[]' WHERE photo_injection_features IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'photo_injection_features')
    op.drop_column('agents', 'photo_injection_enabled')
    op.create_table('conversation_messages',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('run_id', sa.VARCHAR(), nullable=False),
    sa.Column('from_agent_id', sa.VARCHAR(), nullable=False),
    sa.Column('to_agent_id', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('message_type', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_messages_to_agent_id', 'conversation_messages', ['to_agent_id'], unique=False)
    op.create_index('ix_conversation_messages_timestamp', 'conversation_messages', ['timestamp'], unique=False)
    op.create_index('ix_conversation_messages_run_id', 'conversation_messages', ['run_id'], unique=False)
    op.create_index('ix_conversation_messages_from_agent_id', 'conversation_messages', ['from_agent_id'], unique=False)
    # ### end Alembic commands ###
